BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Users] ADD CONSTRAINT [DF__Users__IsSignedIn] DEFAULT 0 FOR [IsSignedIn], CONSTRAINT [DF__Users__Role] DEFAULT 0 FOR [Role];

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN 
    ROLLBACK TRAN;
END;
THROW

END CATCH
